import { ShieldConfig, getBotsToBlock, BotDefinition } from './config';

export { getBotsToBlock };

export function generateRobotsTxt(config: ShieldConfig): string {
  const botsToBlock = getBotsToBlock(config);
  let content = '# Block AI crawlers\n# Generated by ai-crowl-shield\n\n';

  // Add blocked bots
  for (const bot of botsToBlock) {
    content += `# ${bot.description}\n`;
    content += `User-agent: ${bot.userAgent}\n`;
    content += `Disallow: /\n\n`;
  }

  // Add custom rules
  if (config.customRules && config.customRules.length > 0) {
    content += '# Custom rules\n';
    for (const rule of config.customRules) {
      content += `User-agent: ${rule.userAgent}\n`;
      for (const line of rule.rules) {
        content += `${line}\n`;
      }
      content += '\n';
    }
  }

  // Add sitemap
  if (config.sitemap) {
    const sitemaps = Array.isArray(config.sitemap) ? config.sitemap : [config.sitemap];
    for (const sitemap of sitemaps) {
      content += `Sitemap: ${sitemap}\n`;
    }
    content += '\n';
  }

  // Allow all other bots
  content += '# Allow all other bots\n';
  content += 'User-agent: *\n';
  content += 'Allow: /\n';

  return content;
}

export function detectFramework(): 'nextjs' | 'react' | 'vue' | 'static' | null {
  const fs = require('fs');
  const path = require('path');
  const rootDir = process.cwd();

  // Check for Next.js
  if (
    fs.existsSync(path.join(rootDir, 'next.config.js')) ||
    fs.existsSync(path.join(rootDir, 'next.config.mjs')) ||
    fs.existsSync(path.join(rootDir, 'next.config.ts'))
  ) {
    return 'nextjs';
  }

  // Check package.json for framework dependencies
  try {
    const packageJsonPath = path.join(rootDir, 'package.json');
    if (fs.existsSync(packageJsonPath)) {
      const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
      const deps = { ...packageJson.dependencies, ...packageJson.devDependencies };

      if (deps['next']) return 'nextjs';
      if (deps['@vue/cli-service'] || deps['vite'] && deps['vue']) return 'vue';
      if (deps['react-scripts'] || deps['react']) return 'react';
    }
  } catch (error) {
    // Ignore errors
  }

  // Default to static if public directory exists
  if (fs.existsSync(path.join(rootDir, 'public'))) {
    return 'static';
  }

  return null;
}

export function getPublicDir(config: ShieldConfig): string {
  const path = require('path');
  const rootDir = process.cwd();

  if (config.publicDir) {
    return path.join(rootDir, config.publicDir);
  }

  const framework = config.framework === 'auto' ? detectFramework() : config.framework;

  switch (framework) {
    case 'nextjs':
    case 'react':
    case 'static':
      return path.join(rootDir, 'public');
    case 'vue':
      return path.join(rootDir, 'public');
    default:
      return path.join(rootDir, 'public');
  }
}

export function formatBotList(bots: any[]): string {
  let output = '';
  for (const bot of bots) {
    output += `  - ${bot.name}: ${bot.description}\n`;
  }
  return output;
}
